'use client';
import { useCallback, useEffect, useState } from 'react';
import { LiveActivity } from '../../components/admin/LiveActivity';
import { MetricCards } from '../../components/admin/MetricCards';
import { HealthStatus } from '../../components/admin/HealthStatus';
import { MaintenanceSwitch } from '../../components/admin/MaintenanceSwitch';
import { MomentModerationGrid } from '../../components/admin/MomentModerationGrid';
import { SponsorMetrics } from '../../components/admin/SponsorMetrics';
import { FunnelSummary } from '../../components/analytics/FunnelSummary';

type Summary = { event: { name: string; status: string }; metrics: { participants: number; moments: number; published: number; hidden: number }; activity: Array<{ id: string; at: string; label: string }> };
type Health = { overall: string; checks: Array<{ component: string; label: string; status: string; latencyMs: number }> };
type Moment = { id: string; category: string | null; status: string; participantName: string; participantBatch: string; hiddenReason: string | null };
type Analytics = { funnel: React.ComponentProps<typeof FunnelSummary>['summary']; sponsor: React.ComponentProps<typeof SponsorMetrics>['summary'] };

async function json<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); const payload = await response.json() as { data?: T; error?: { message?: string } }; if (!response.ok || payload.data === undefined) throw new Error(payload.error?.message ?? 'Permintaan admin gagal.'); return payload.data; }
function csrf() { return decodeURIComponent(document.cookie.split('; ').find((item) => item.startsWith('invnity_csrf='))?.split('=').slice(1).join('=') ?? ''); }

export function AdminConsole({ section = 'dashboard' }: { section?: 'dashboard' | 'moments' | 'participants' }) {
  const [summary, setSummary] = useState<Summary | null>(null); const [health, setHealth] = useState<Health | null>(null); const [analytics, setAnalytics] = useState<Analytics | null>(null); const [moments, setMoments] = useState<Moment[]>([]); const [error, setError] = useState(''); const [login, setLogin] = useState(false); const [busy, setBusy] = useState(false); const [email, setEmail] = useState(''); const [token, setToken] = useState(''); const [query, setQuery] = useState('');
  const load = useCallback(async () => { try { setError(''); const [nextSummary, nextHealth] = await Promise.all([json<Summary>('/api/v1/admin/summary'), json<Health>('/api/v1/admin/health')]); setSummary(nextSummary); setHealth(nextHealth); try { setAnalytics(await json<Analytics>('/api/v1/admin/analytics')); } catch { setAnalytics(null); } if (section === 'moments') setMoments(await json<Moment[]>('/api/v1/admin/moments?visibility=recent')); } catch (reason) { const message = reason instanceof Error ? reason.message : 'Akses operator diperlukan.'; const needsLogin = message.includes('operator') || message.includes('Akses'); setLogin(needsLogin); setError(needsLogin ? '' : message); } }, [section]);
  useEffect(() => { void load(); }, [load]);
  const signIn = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { await json('/api/v1/admin/session', { method: 'POST', headers: { 'content-type': 'application/json', 'x-csrf-token': csrf() }, body: JSON.stringify({ email, accessToken: token }) }); setLogin(false); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Login admin gagal.'); } finally { setBusy(false); } };
  const changeMode = async (mode: 'live' | 'maintenance' | 'archived') => { setBusy(true); try { await json('/api/v1/admin/event-mode', { method: 'PATCH', headers: { 'content-type': 'application/json', 'x-csrf-token': csrf() }, body: JSON.stringify({ mode }) }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Mode acara gagal diubah.'); } finally { setBusy(false); } };
  if (login) return <section className="admin-panel admin-login"><h1>Akses operator</h1><p className="muted-copy">Masukkan email admin dan access token yang tersimpan di environment Vercel.</p><form onSubmit={(event) => void signIn(event)}><label className="admin-label">Email<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></label><label className="admin-label">Access token<input type="password" required value={token} onChange={(event) => setToken(event.target.value)} /></label><button className="primary-button full-button" disabled={busy} type="submit">Masuk</button></form>{error && <p className="error-message" role="alert">{error}</p>}</section>;
  if (!summary) return <p className="muted-copy">Memuat operasi acara…</p>;
  if (section === 'moments') return <><div className="page-header"><div><p className="eyebrow">InVnity Moments</p><h1>Moderasi momen</h1></div><a className="text-link" href="/admin">Dashboard</a></div><MomentModerationGrid moments={moments} onVisibility={async (moment, visibility, reason) => { await json(`/api/v1/admin/moments/${moment.id}/visibility`, { method: 'PATCH', headers: { 'content-type': 'application/json', 'x-csrf-token': csrf() }, body: JSON.stringify({ visibility, reason }) }); setError('Foto disembunyikan.'); setMoments(await json<Moment[]>('/api/v1/admin/moments?visibility=recent')); }} />{error && <p className="success-message">{error}</p>}</>;
  if (section === 'participants') return <><div className="page-header"><div><p className="eyebrow">InVnity Moments</p><h1>Peserta</h1></div><a className="text-link" href="/admin">Dashboard</a></div><form className="admin-search" onSubmit={(event) => { event.preventDefault(); void json<Array<{ id: string; name: string; batch: string; momentCount: number }>>(`/api/v1/admin/participants?q=${encodeURIComponent(query)}`).then((rows) => setMoments(rows.map((row) => ({ id: row.id, participantName: row.name, participantBatch: row.batch, category: null, status: String(row.momentCount), hiddenReason: null })))).catch((reason) => setError(reason instanceof Error ? reason.message : 'Pencarian gagal.')); }}><input aria-label="Cari peserta" type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari nama atau angkatan" /><button className="secondary-button" type="submit">Cari peserta</button></form><div className="admin-list">{moments.map((item) => <div className="admin-list-row" key={item.id}><strong>{item.participantName}</strong><span>Angkatan {item.participantBatch} · {item.status} momen</span></div>)}</div></>;
  return <><div className="page-header"><div><p className="eyebrow">InVnity Moments</p><h1>Operasi acara</h1></div><span className="brand-mark">InV<span>V</span>nity</span></div><section className="moments-hero admin-hero"><p className="eyebrow">{summary.event.status}</p><h2>{summary.event.name}</h2><MetricCards metrics={summary.metrics} /></section><MaintenanceSwitch mode={summary.event.status} onChange={(mode) => void changeMode(mode)} busy={busy} />{analytics && <><FunnelSummary summary={analytics.funnel} /><SponsorMetrics summary={analytics.sponsor} /></>}<HealthStatus health={health} /><LiveActivity activity={summary.activity} /><nav className="admin-links"><a className="secondary-button" href="/admin/moments">Moderasi</a><a className="secondary-button" href="/admin/participants">Peserta</a></nav></>;
}
